tasks:
  - name: Terminal
    openMode: split-left
    before: cd /workspace/TonalHub/TonalHub
  - name: "Dev Servers"
    openMode: split-right
    before: |
      cd /workspace/TonalHub/TonalHub
    init: yarn install
    command: yarn rw dev --fwd="--client-web-socket-url=ws$(gp url 8910 | cut -c 5-)/ws"

ports:
  - port: 8910
    onOpen: open-browser
    visibility: public
  - port: 8911
    onOpen: ignore
    visibility: public