image: gitpod/workspace-postgres:latest

tasks:
  - name: Dev Servers
    init: yarn install
    command: yarn rw dev --fwd="--client-web-socket-url=ws$(gp url 8910 | cut -c 5-)/ws"

  - name: Prisma Studio
    command: yarn rw prisma studio

  - name: Terminal

ports:
  - port: 5432
    name: DB
    onOpen: ignore
  - port: 5555
    name: Prisma Studio
    onOpen: open-browser
    visibility: public
  - port: 8910
    name: WebUI
    onOpen: open-browser
    visibility: public
  - port: 8911
    name: API
    onOpen: ignore
    visibility: public
