checkoutLocation: TonalHub
workspaceLocation: .

tasks:
  - name: Terminal
    openMode: split-left
    before: |
      export RWFW_PATH="/workspace/TonalHub"
      export RWJS_DEV_API_URL="http://localhost"
      cd /workspace/TonalHub/TonalHub
  - name: "Dev Servers"
    openMode: split-right
    before: |
      export RWFW_PATH="/workspace/TonalHub/TonalHub"
      export RWJS_DEV_API_URL="http://localhost"
      export REDWOOD_DISABLE_TELEMETRY=1
    init: |
      cd /workspace/TonalHub/TonalHub
      yarn install
    command: |
      cd /workspace/rw-test-app
      yarn rw dev

ports:
  - port: 8910
    onOpen: open-browser
  - port: 8911
    onOpen: ignore
    visibility: public