tasks:
  - name: Terminal
    openMode: split-left
    before: |
      export RWFW_PATH="/workspace/TonalHub"
      export RWJS_DEV_API_URL="http://localhost"
      cd /workspace/TonalHub/TonalHub
  - name: "Dev Servers"
    openMode: split-right
    before: |
      export RWFW_PATH="/workspace/TonalHub/TonalHub"
      export RWJS_DEV_API_URL="http://localhost"
      export REDWOOD_DISABLE_TELEMETRY=1
      cd /workspace/TonalHub/TonalHub
    init: yarn install
    command: yarn rw dev

ports:
  - port: 8910
    onOpen: open-browser
  - port: 8911
    onOpen: ignore
    visibility: public