tasks:
  - name: Terminal
    openMode: split-left
    before: cd /workspace/TonalHub/TonalHub
  - name: "Dev Servers"
    openMode: split-right
    before: |
      cd /workspace/TonalHub/TonalHub
    init: yarn install
    command: yarn rw dev --fwd="--allowed-hosts localhost --allowed-hosts $(gp url 8910 | sed -e "s/https:\/\///g") --host 0.0.0.0 --client-web-socket-url=$(gp url 8910 | sed -e "s/https/wss/g")"

ports:
  - port: 8910
    onOpen: open-browser
  - port: 8911
    onOpen: ignore
    visibility: public