tasks:
  - name: Terminal
    before: cd /workspace/TonalityLab/TonalityLab
    command: alias rw='yarn redwood'
  - name: "Dev Servers"
    before: cd /workspace/TonalityLab/TonalityLab
    init: yarn install
    command: yarn rw dev --fwd="--client-web-socket-url=ws$(gp url 8910 | cut -c 5-)/ws"

ports:
  - port: 8910
    onOpen: open-browser
    visibility: public
  - port: 8911
    onOpen: ignore
    visibility: public